apiVersion: storage.coreos.com/v1alpha1
kind: StorageCluster
metadata:
    name: mock
spec:
    type: mock
    storageNodes:
        - nodeName: node1.example.com
          directories:
              - /export
        - directories:
              - /export
          nodeName: node2.example.com
